name: Build and push Docker
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push to github registry
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: rewatch-stack
          dockerfile: Dockerfile
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}